# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Ananke Extend Theme"
license = "MIT"
licenselink = "https://github.com/wikty/hugo-ananke-ext/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/wikty/hugo-ananke-ext"
tags = ["website", "starter", "responsive"]
features = ["posts", "shortcodes"]
min_version = 0.37

[author]
  name = "Xiao Wenbin"
  homepage = "https://github.com/wikty"
